# 本地开发环境配置文件
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/game?autoreconnect=true&useSSL=false"
    username: "game"
    password: "game123"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

flyway:
  url: "jdbc:mysql://127.0.0.1:3306/game?autoreconnect=true&useSSL=false"
  schemas: game
  user: "game"
  password: "game123"