apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sjg

images:
  - name: sjg-data-backend
    newName: sjg-data-backend
    newTag: latest

bases:
  - ../../base

resources:
  - ingress.yaml
  - service.yaml

patchesStrategicMerge:
  - replicas_count.yaml
  - set_image.yaml
  - set_resource.yaml
  - set_env.yaml
